name: e2e
on:
  pull_request:
    branches: [ "main" ]
jobs:
  e2e:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    name: e2e
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: '1.25'
    - uses: helm/kind-action@v1.13.0
      with:
        install_only: true
    - uses: ko-build/setup-ko@v0.9
    - name: Setup CAPK management and tenant clusters
      shell: bash
      run: |
        ./test/hack/e2e.sh
      env:
        KIND_CLUSTER_IMAGE: kindest/node:v1.32.8
    - name: cleanup 
      shell: bash
      run: | 
        kind delete cluster --name km-cp
        kind delete cluster
